[package]
name = "xcg-coding-game"
version = "0.1.0"
keywords = ["xcg", "coding", "game"]
authors = ["Nick Linker <nlinker@gmail.com>"]

[lib]
name = "xcg"

[[bin]]
name = "xcg-app"
path = "src/main.rs"

[dependencies]
itertools = "0.7.8"
